-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 14:01:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clockwise
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clockwise` ;

-- -----------------------------------------------------
-- Schema clockwise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clockwise` DEFAULT CHARACTER SET utf8 ;
USE `clockwise` ;

-- -----------------------------------------------------
-- Table `clockwise`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`t_user` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`t_user` (
  `u_id` INT NOT NULL,
  `u_username` VARCHAR(45) NOT NULL,
  `u_email` VARCHAR(45) NOT NULL,
  `u_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clockwise`.`t_teamleader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`t_teamleader` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`t_teamleader` (
  `tl_u_user` INT NOT NULL,
  PRIMARY KEY (`tl_u_user`),
  CONSTRAINT `fk_t_teamleader_t_user1`
    FOREIGN KEY (`tl_u_user`)
    REFERENCES `clockwise`.`t_user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clockwise`.`t_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`t_project` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`t_project` (
  `p_id` INT NOT NULL,
  `p_name` VARCHAR(45) NOT NULL,
  `p_t_teamleader` INT NOT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `fk_t_project_t_teamleader1_idx` (`p_t_teamleader` ASC),
  CONSTRAINT `fk_t_project_t_teamleader1`
    FOREIGN KEY (`p_t_teamleader`)
    REFERENCES `clockwise`.`t_teamleader` (`tl_u_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clockwise`.`t_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`t_entry` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`t_entry` (
  `e_id` INT NOT NULL,
  `e_startTime` DATETIME NOT NULL,
  `e_endtime` DATETIME NOT NULL,
  `e_description` VARCHAR(45) NOT NULL,
  `e_p_project` INT NOT NULL,
  `e_u_user` INT NOT NULL,
  PRIMARY KEY (`e_id`),
  INDEX `fk_e_entry_t_project1_idx` (`e_p_project` ASC),
  INDEX `fk_e_entry_t_user1_idx` (`e_u_user` ASC),
  CONSTRAINT `fk_e_entry_t_project1`
    FOREIGN KEY (`e_p_project`)
    REFERENCES `clockwise`.`t_project` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_e_entry_t_user1`
    FOREIGN KEY (`e_u_user`)
    REFERENCES `clockwise`.`t_user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clockwise`.`t_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`t_tag` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`t_tag` (
  `ta_id` INT NOT NULL,
  `ta_name` VARCHAR(45) NOT NULL,
  `ta_p_project` INT NOT NULL,
  `ta_e_entry` INT NOT NULL,
  PRIMARY KEY (`ta_id`, `ta_p_project`),
  INDEX `fk_t_tag_t_project1_idx` (`ta_p_project` ASC),
  INDEX `fk_t_tag_e_entry1_idx` (`ta_e_entry` ASC),
  CONSTRAINT `fk_t_tag_t_project1`
    FOREIGN KEY (`ta_p_project`)
    REFERENCES `clockwise`.`t_project` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_tag_e_entry1`
    FOREIGN KEY (`ta_e_entry`)
    REFERENCES `clockwise`.`t_entry` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clockwise`.`u_p_userProjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`u_p_userProjects` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`u_p_userProjects` (
  `pu_project` INT NOT NULL,
  `pu_user` INT NOT NULL,
  PRIMARY KEY (`pu_project`, `pu_user`),
  INDEX `fk_t_project_has_t_user_t_user1_idx` (`pu_user` ASC),
  INDEX `fk_t_project_has_t_user_t_project1_idx` (`pu_project` ASC),
  CONSTRAINT `fk_t_project_has_t_user_t_project1`
    FOREIGN KEY (`pu_project`)
    REFERENCES `clockwise`.`t_project` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_project_has_t_user_t_user1`
    FOREIGN KEY (`pu_user`)
    REFERENCES `clockwise`.`t_user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clockwise`.`t_todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clockwise`.`t_todo` ;

CREATE TABLE IF NOT EXISTS `clockwise`.`t_todo` (
  `td_e_id` INT NOT NULL,
  `td_estimatedTime` DATETIME NOT NULL,
  `td_u_user` INT NOT NULL,
  PRIMARY KEY (`td_e_id`),
  INDEX `fk_t_todo_t_user1_idx` (`td_u_user` ASC),
  CONSTRAINT `fk_t_todo_e_entry1`
    FOREIGN KEY (`td_e_id`)
    REFERENCES `clockwise`.`t_entry` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_todo_t_user1`
    FOREIGN KEY (`td_u_user`)
    REFERENCES `clockwise`.`t_user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
